### ISSUE TITLE
Card not showing anything

### ISSUE THREAD

**Issue by TheGreatBorg** [ljmerza/fitbit-card#2]
I have installed the component and added these lines into Raw text editor in UL-Lovelace

```
resources:
  - type: module
    url: /community_plugin/fitbit-card/fitbit-card.js
```

![image](https://user-images.githubusercontent.com/31419036/60819648-3d7dba80-a1a0-11e9-88e4-a6495c4de05b.png)

But nothing shows when activated - only my manually added sensors card in the top:
![image](https://user-images.githubusercontent.com/31419036/60819913-b4b34e80-a1a0-11e9-958b-1e7a3f7c0413.png)

**Comment by TheGreatBorg** [comment]
Here is my Raw setup in UI-Lovelace

![image](https://user-images.githubusercontent.com/31419036/60880785-a0c12880-a244-11e9-9dbf-acbb3a00f15a.png)

![image](https://user-images.githubusercontent.com/31419036/60888924-20a4be00-a258-11e9-9e72-21b42a7daad8.png)

**Comment by ljmerza** [comment]
type is js. Didnt realize HACS adds modue by default

**Comment by TheGreatBorg** [comment]
Well I did add that because without nothing worked and then I got advised in Discord to add type and "module" sounded right. 

You see this was added via UI-Lovelace Raw text editor not in yaml files. I try to avoid yaml files (I hate them) - but still with or without a type setting the card still don't show anything

**Comment by Lethal83** [comment]
Hi all. Im having the exact same issue.

**Comment by ljmerza** [comment]
Are there any errors in the console?

**Comment by ljmerza** [comment]
@TheGreatBorg have you gotten this working? Try just adding the most basic config to see if that works.

**Comment by Lethal83** [comment]
Hi
I didnt see any errors in the console
but what i did was strip it all back out to the basic config and added one
line at a time.
I think my issue is not with your card but missing data from fitbit.
When i added in the calories and active minutes is when my card goes blank.
if i look at what data was coming in from fitibit to HA there is no data.
Ill look into that and let you know if it fixes it.

**Comment by Lethal83** [comment]
Update: I was missing a couple of sensors (From https://www.home-assistant.io/components/fitbit/) 
I added them all in instead of the selected ones and now its working. thanks
