### ISSUE TITLE
Where to put the below info:

### ISSUE THREAD

**Issue by JePeSWE** [ljmerza/fitbit-card#4]
Add the following to resources in your lovelace config:

resources:
  - url: /community_plugin/fitbit-card/fitbit-card.js
    type: js
Where do i put that info?

And this:
type: 'custom:fitbit-card'
battery_entity: sensor.versa_battery
header_entities:
  - entity: sensor.tracker_steps
    icon_color: '#14308D'
  - entity: sensor.distance
    show_units: true
  - entity: sensor.tracker_calories
    icon_color: red
entities:
  - entity: sensor.minutes_sedentary
    max: 1000
  - entity: sensor.minutes_very_active
    max: 120
  - entity: sensor.minutes_lightly_active
    max: 50
    color_stops:
      '0': red
      '50': yellow
      '90': green
  - entity: sensor.resting_heart_rate
    show_units: true

**Comment by ljmerza** [comment]
install the card through HACS and add the yaml configuration
